name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make get-stockfish
      working-directory: ./src
      run: make get-stockfish
    - name: make
      working-directory: ./src
      run: make
    - name: test
      working-directory: ./src
      run: ./cha test
