name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Download Stockfish
      working-directory: ./lib/stockfish
      run: make get-stockfish
    - name: Compile Stockfish
      working-directory: ./lib/stockfish
      run: make
    - name: Install Stockfish
      working-directory: ./lib/stockfish
      run: sudo make install
    - name: Enable shared libraries
      run: sudo /sbin/ldconfig -v
    - name: make
      working-directory: ./src
      run: make
    - name: test
      working-directory: ./src
      run: ./cha test
